import Head from "next/head";
import Header from "../components/layout/Header";
import Matches from "../components/matches/Matches";
import News from "../components/news/News";
import Standing from "../components/standings/Standing";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Matches />
      {/* <News /> */}
      {/* <Standing /> */}
    </div>
  );
}
